# Generated by Django 4.2.20 on 2025-07-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
